version: '3'
services:
  spc:
    container_name: 'scrumpokerclub.app'
    build:
      context: .
      dockerfile: ./ScrumPokerClub.App/Dockerfile
    ports:
      - 443:5001
    volumes:
      # Mount the appsettings file instead of baking it into the image.
      - ./ScrumPokerClub.App/appsettings.json:/app/appsettings.json
      # Mount the local data directory.
      - ./.appdata/:/root/.local/share/
      # Certs will be created if it doesn't exist, and may be left empty if not using HTTPS.
      - ./certs/:/app/tls/
    restart: always
