// <auto-generated />
using System;
using Flush.Databases.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Flush.Databases.Application.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210106140337_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Flush.Databases.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditLogId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Flush.Databases.Entities.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Flush.Databases.Entities.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AspNetIdentity")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsObserver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Vote")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Flush.Databases.Entities.AuditLog", b =>
                {
                    b.HasOne("Flush.Databases.Entities.Game", "Game")
                        .WithMany("AuditLogs")
                        .HasForeignKey("GameId");

                    b.HasOne("Flush.Databases.Entities.Player", "Player")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Flush.Databases.Entities.Player", b =>
                {
                    b.HasOne("Flush.Databases.Entities.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Flush.Databases.Entities.Game", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Flush.Databases.Entities.Player", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
