// <auto-generated />
using System;
using Flush.Data.Game.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Flush.Migrations
{
    [DbContext(typeof(FlushContext))]
    partial class FlushContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("Flush.Data.Game.Model.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditLogId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Flush.Data.Game.Model.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Flush.Data.Game.Model.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AspNetIdentity")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsObserver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Vote")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Flush.Data.Game.Model.AuditLog", b =>
                {
                    b.HasOne("Flush.Data.Game.Model.Game", "Game")
                        .WithMany("AuditLogs")
                        .HasForeignKey("GameId");

                    b.HasOne("Flush.Data.Game.Model.Player", "Player")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("Flush.Data.Game.Model.Player", b =>
                {
                    b.HasOne("Flush.Data.Game.Model.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId");
                });
#pragma warning restore 612, 618
        }
    }
}
